### ISSUE TITLE
Game completely screws up after using magic mirror

### ISSUE THREAD

**Issue by Wuzzy2** [D00Med/LegendofMinetest#18]
If you use the magic mirror, the game just completely screws up:

First, it teleports you to a strange red biome (so far so good), but you spawn WAY above ground (it's a wonder you survive the drop).
But soon after you teleport, the place is quickly overpopulated with hundreds of mobs, and Minetest becomes really slow. I sometimes see that Minetest attempts to delete entities because of overcrowded areas. Sometimes Minetest stops responding altogehter, and I have to restart.

It's pretty safe to say that using the magic mirror at the current stage is making the game very unstable.

Tested in v2.

**Comment by D00Med** [comment]
I fixed the mobs spawning.
I don't really know how to get around the player falling or being buried without checking a lot of nodes to see if they are safe

**Comment by mckaygerhard** [comment]
i tested after the pull #39 was merge.. **all the issues about overpopulated spawn was solved..** so this issue must be closed ..  **but now i cannot find any mob there so this issue must generated a new one** 

**after some research the issue is a slow map generation that's all**, the mirror definition tries to guess the layer and assumed its under 21000 but try the 21500 is ok and if there's no good point try again under 21000, cos in init.lua of hell (caverealm based) mod, there's MIN and MAX levels.. **so then and let the player to fall if mana is enough.. so i guess this issue is soft resolved @Wuzzy2  now the only issue is the lack of mobs generation** inclusively i upgrade the mobs_redo to last from tenplus1

discovered new issues: **missing depends** (unrelated to this issue) it depends on `mana` due the check of mana in player on the mirror magic item definition, and second, after some code search i find that the layer is the "hell" generated by  `hyrule_mapgen` and `hell` mods so there's then **two missing depends: mana and hell**..  after this i have a idea, defined a big lava fall that covers the area and if player is not enough fast then will be covered XD but will get more slow the minetest engine XD

**so this issue can be closed .. the pull #39 was merge.. to start to port to 5.0.1 and to start to be stable in 0.4.17, thanks in advance @D00Med  (lest remenber only port and stability for now)**
