### ISSUE TITLE
[bug] quartz sound must be table not just string of the file, for neweer engines

### ISSUE THREAD

**Issue by hacknorris-code** [D00Med/LegendofMinetest#45]
bug : 

![Przechwycenie obrazu ekranu_2022-06-21_18-55-59](https://user-images.githubusercontent.com/97974194/174856104-ca4f3fd3-300c-45a5-aeec-f17010035a09.png)

o.O

[debug.txt](https://github.com/D00Med/LegendofMinetest/files/8950925/debug.txt)

**Comment by mckaygerhard** [comment]
the  5.5 changes a lot the api.. poikilos already talk about the constants changes at https://poikilos.org/2020/05/09/minetest-scope-issue/ i am able to run "LOM" until 5.2 only... for 5.4 and 5.5  some time will pass.. i currently study the defaults mod changes to provide backported changes.. 

.. so about the error `quarzt` .. a mineral.. at `register_slab("quartzstair", "quartz:pillar",` sound must be a table since 5.4 as https://github.com/minetest/minetest/blob/5.4.0/doc/lua_api.txt#L7270 . so fix are just a "{" and "}" around.. but i will do not that yet.. as i explained previously cos i will maintain blackguard compatibility.. 

```
2022-06-21 18:55:50: ERROR[Main]: ...me\minetest-5.5.1-win64\bin\..\builtin\game\register.lua:184: bad argument #5 to 'register_item_raw' (table expected, got string)
```

**but noted that `E:\game\minetest-5.5.1-win64` i do not officially support guindows.. so i will test only for linux .. noted you run xfce4 maybe you runs minetest 5.5 emulated but there's some packages in OBS build service... so for valids bug i will only fix linux debugs.**. 

marked as bug cos are valid but fix will be not so yet .. cos already works in 5.2

**Comment by hacknorris-code** [comment]
ok. 
yes i "emulated" USING W.I.N.E. lool
